### PR TITLE
fixed: fix collision of div by changing from flex to grid

### PR DESCRIPTION
**Pull request by K3ndev**
Hi, I've made some changes to fix an issue where div elements were colliding on the projects page.

### CODE REVIEW

**Comment by jofftiquez** [comment]
Hi @K3ndev thanks for you this, can you provide a screenshot of the updated design? I haven't setup any test preview yet. Thanks

**Comment by K3ndev** [comment]
Sure, I've attached a screenshot of the updated UI that fixed the issues with the previous layout, and I've also included the dimensions that were causing the problem.

fix-19

**Comment by K3ndev** [comment]
This is the previous layout: 1072x831

image

**Comment by K3ndev** [comment]
Sure, I've attached a screenshot of the updated UI that fixed the issues with the previous layout
<details>
<summary>before</summary>

1072x831
image

</details>

<details>
<summary>after</summary>

image

</details>

**Comment by K3ndev** [comment]
Sure, I've attached a screenshot of the updated UI that fixed the issues with the previous layout
<details>
<summary>before</summary>

1072x831
image

</details>

<details>
<summary>after</summary>

image

</details>

**Review by jofftiquez — APPROVED** [review]
Looks good. Thanks for providing the screenshots. Merging this onw.

**Pull request merged**
